name: Vercel Production

on:
  push:
    branches:
      - master

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      # working-directory: apps/docs   # uncomment + set if in subfolder

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Env (Production)
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build (prebuilt)
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (production)
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
